version: '3.1'

services:
  grpc:
    build:
      context: .
      dockerfile: grpc.Dockerfile
    depends_on:
      - db
    ports:
      - "50051:50051"

  httpgateway:
    build:
      context: .
      dockerfile: httpgateway.Dockerfile
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5442:5432"
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: